groups:
  # cloudwego family
  - name: "cloudwego"
    orgs:
      - "cloudwego"
      - "kitex-contrib"
      - "hertz-contrib"
      - "volo-rs"
    repos:
      - "bytedance/sonic"
      - "bytedance/monoio"
  # test group
#  - name: "rainiring"
#    orgs:
#      - "rainiring"
datasource:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "114514"
    database: "openalysis?charset=utf8&parseTime=True&loc=Local"
backend:
  cron: "@daily"
  token: ""
  retry: 3