groups:
  # cloudwego family
  - name: "cloudwego"
    orgs:
      - "cloudwego"
      - "kitex-contrib"
      - "hertz-contrib"
      - "volo-rs"
    repos:
      - "bytedance/sonic"
      - "bytedance/monoio"
datasource:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "114514"
    database: "openalysis?charset=utf8&parseTime=True&loc=Local"
backend:
  cron: "@daily"
  # delete after presentation
  token: "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"
  retry: 3
cleaner:
  - "`@CloudWeGo` => `CloudWeGo`"
  - "`Bytedance` => `ByteDance`"
  - "`@bytedance` => `ByteDance`"
  - "`@Bytedance` => `ByteDance`"
  - "`Bytedance Inc` => `ByteDance`"
  - "`Shanghai` => `Shanghai, China`"
  - "`BeiJing` => `Beijing, China`"
  - "`Hangzhou` => `Hangzhou, China`"
  - "`GuangZhou, China` => `Guangzhou, China`"
