groups:
  - name: "hello"
    orgs:
      - "org1"
    repos:
      - "repo1"
      - "repo2"
  - name: "world"
    orgs:
      - "org2"
      - "org3"
    repos:
      - "repo3"
      - "repo4"
      - "repo5"
datasource:
  mysql:
    host: "localhost"
    port: "3306"
    user: "root"
    password: "114514"
    database: "openalysis"
backend:
  frequency: 3
  token: ""