groups:
  # cloudwego family
  - name: "cloudwego"
    orgs:
      - "cloudwego"
      - "kitex-contrib"
      - "hertz-contrib"
      - "volo-rs"
    repos:
      - "bytedance/sonic"
      - "bytedance/monoio"
datasource:
  mysql:
    host: "mysql"
    port: "3306"
    user: "openalysis"
    password: "openalysis"
    database: "openalysis?charset=utf8&parseTime=True&loc=Local"
backend:
  cron: "@daily"
  token: "your-github-token"
  retry: 3
# "`Before` => `After`"
cleaner:
  - "`@CloudWeGo` => `CloudWeGo`"
  - "`@cloudwego` => `CloudWeGo`"
  - "`Bytedance` => `ByteDance`"
  - "`@bytedance` => `ByteDance`"
  - "`@Bytedance` => `ByteDance`"
  - "`@ByteDance` => `ByteDance`"
  - "`Bytedance Inc` => `ByteDance`"
  - "`@tencent` => `Tencent`"
  - "`Shanghai` => `Shanghai, China`"
  - "`BeiJing` => `Beijing, China`"
  - "`Beijing` => `Beijing, China`"
  - "`beijing` => `Beijing, China`"
  - "`Hangzhou` => `Hangzhou, China`"
  - "`HangZhou` => `Hangzhou, China`"
  - "`hangzhou` => `Hangzhou, China`"
  - "`GuangZhou, China` => `Guangzhou, China`"
  - "`chongqing` => `Chongqing, China`"
  - "`中国` => `Other, China`"
  - "`China` => `Other, China`"
# "`login`, `company`, `location`"
# e.g. "`justlorain`, `binary`, ``"
# `` means do not update location
marker:
  - "`sample user`, `sample company`, `sample location`"
