version: "3.7"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=openalysis
      - MYSQL_USER=openalysis
      - MYSQL_PASSWORD=openalysis
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  openalysis:
    build: .
    command: ["start", "-c", "@hourly", "-t", "token", "default.yaml"]
    depends_on:
      - mysql
      - grafana